# Generated by Django 4.0 on 2023-09-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_comment_post'),
        ('blog_app', '0002_alter_post_slug'),
    ]

    operations = [
    ]
